[package]
name = "integral_rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["WhiskyAKM"]
repository = "https://github.com/PTFOPlayer/integrl_rs"
description = "Simple liblary for solving integrals using numerical methods"
categories = ["math"]
keywords = ["integral", "math", "numeric"]

[dependencies]
